server:
  port: 8084
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/javap?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
#
#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.szxj.db.entity
#

